# Generated by Django 4.2.11 on 2024-04-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(help_text='Informe o nome de usuário', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Informe o nome', max_length=100)),
                ('email', models.EmailField(help_text='Informe o email', max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, help_text='Informe o numéro de telefone', max_length=20, null=True)),
                ('dataNascimento', models.DateField(blank=True, help_text='Informe a data de nascimento', null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], help_text='Informe o sexo', max_length=1, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
    ]
