# Generated by Django 4.2.11 on 2024-06-03 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_name_user_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nome',
        ),
    ]
