# Generated by Django 4.2.11 on 2024-06-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], help_text='Informe o sexo', max_length=9, null=True),
        ),
    ]
