# Generated by Django 5.0.4 on 2024-04-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('contato', models.CharField(max_length=50)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.CharField(max_length=1000)),
            ],
        ),
    ]
