# Generated by Django 4.2.11 on 2024-05-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='foto_perfil',
            field=models.ImageField(default='default.jpg', upload_to='perfil_instituicao'),
        ),
    ]
