# Generated by Django 4.2.11 on 2024-05-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_institution_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
