# Generated by Django 4.2.4 on 2024-05-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_institution_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='foto_perfil',
        ),
        migrations.AddField(
            model_name='institution',
            name='fotoPerfil',
            field=models.ImageField(default='default.jpg', upload_to='institution'),
        ),
    ]
