# Generated by Django 4.2.11 on 2024-06-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_remove_institution_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(default='default@mail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='logged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
