# Generated by Django 5.0.6 on 2024-06-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_institution_email_institution_logged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
