# Generated by Django 5.0.6 on 2024-06-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='fotoPerfil',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='scholarship'),
        ),
    ]
