# Generated by Django 5.0.6 on 2024-06-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_alter_scholarship_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='fotoPerfil',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media/scholarship'),
        ),
    ]
