# Generated by Django 4.2.11 on 2024-06-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_alter_scholarship_fotoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='dataPrazo',
            field=models.DateField(default='2020-01-01', help_text='Data limite para a realização da bolsa', verbose_name='Data limite'),
        ),
    ]
