# Generated by Django 4.2.11 on 2024-06-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0005_scholarship_dataprazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='dataPrazo',
            field=models.DateField(help_text='Data limite para a realização da bolsa', verbose_name='Data limite'),
        ),
    ]
