# Generated by Django 5.0.6 on 2024-06-30 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0006_alter_scholarship_dataprazo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='inscritos',
            field=models.ManyToManyField(related_name='scholarships', to=settings.AUTH_USER_MODEL),
        ),
    ]
