# Generated by Django 5.0.6 on 2024-06-30 03:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0007_scholarship_inscritos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='inscritos',
            field=models.ManyToManyField(related_name='scholarships_inscritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
